"""
HPA Axis Wavelet Spectrograms — All Participants

Plots the wavelet power spectrograms for all ten participants in a single figure.
Reads the pre-computed stacked wavelet arrays produced by wavelet_analysis.py.

Manuscript figures generated by this script
--------------------------------------------
  Figure S2  — Wavelet power spectrograms for all ten participants (circadian-detrended
               CORT, dt=10 min). 5×2 grid, one subplot per participant. Colour scale =
               wavelet power (yellow high, dark blue low); x-axis = time of day;
               y-axis = period (50–300 min).
               Saved: data_analysis/output/Cortisol/10min/wavelet_analysis_all_participants.pdf
               Saved: data_analysis/output/Cortisol/10min/wavelet_analysis_all_participants.png

Usage:
    python data_analysis/code/wavelet_analysis/plot_all_spectrograms.py

    Run wavelet_analysis.py first to generate the required .npy input files.

Input:
    - data_analysis/output/Cortisol/10min/stacked_wavelets_Cortisol.npy
    - data_analysis/output/Cortisol/10min/times.npy
    - data_analysis/output/Cortisol/10min/periods.npy

Output:
    - data_analysis/output/Cortisol/10min/wavelet_analysis_all_participants.pdf
    - data_analysis/output/Cortisol/10min/wavelet_analysis_all_participants.png
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

results_folder = 'data_analysis/output/Cortisol/10min'

stacked_cort = np.load(f'{results_folder}/stacked_wavelets_Cortisol.npy', allow_pickle=True)
times = np.load(f'{results_folder}/times.npy', allow_pickle=True)
periods = np.load(f'{results_folder}/periods.npy', allow_pickle=True)

plt.rcParams.update({"font.size": 24})

plt.figure(figsize=(20, 20))
right_gs = plt.GridSpec(5, 2, wspace=0.15, hspace=0.15)

for i in range(10):
    ax = plt.subplot(right_gs[i // 2, i % 2])
    flipped_wavelet = np.flipud(stacked_cort[i])

    sns.heatmap(flipped_wavelet, cmap="viridis", cbar=True, ax=ax,
                cbar_kws={'orientation': 'vertical', 'shrink': 0.8})

    if i // 2 == 4:
        tick_positions = list(range(6 * 3, 144, 36))  # 18, 54, 90, 126
        tick_labels = [times[j] for j in tick_positions]
        ax.set_xticks(tick_positions)
        ax.set_xticklabels(tick_labels)
    else:
        ax.set_xticks([])

    if i % 2 == 0:
        ax.set_yticks(range(0, 1000, 250))
        ax.set_yticklabels(periods[::-1][::250].round(0))
    else:
        ax.set_yticks([])

    ax.set_title(f"Participant {i + 1}", fontsize=20)

plt.savefig(f'{results_folder}/wavelet_analysis_all_participants.png', dpi=300, bbox_inches='tight')
plt.savefig(f'{results_folder}/wavelet_analysis_all_participants.pdf', dpi=300, bbox_inches='tight')
plt.close()

print(f"Saved: {results_folder}/wavelet_analysis_all_participants.{{png,pdf}}")
