"""
CRH plotting script
Creates either constant CRH panels, single oscillating plots, or side-by-side comparisons.

Requires simulate_crh.py to have been run first to produce the .npy data files.

Manuscript figures generated by this script
--------------------------------------------
  Figure 4B  — Low, Medium and High constant CRH simulations (3-panel)
               Command:
                   python model/analysis/crh_oscillatory/simulate_crh.py constant
                   python model/analysis/crh_oscillatory/plot_crh.py constant
               Saved: model/analysis/crh_oscillatory/output/figures/constant_crh_conditions.pdf

Outputs (in model/analysis/crh_oscillatory/output/figures/):
  constant_crh_conditions.pdf / .png            3 panels: Low/Medium/High constant CRH (Figure 4B)
  oscillating_crh_conditions.pdf / .png         last 24 h, 3-panel (single mode)
  oscillating_crh_conditions_full.pdf / .png    full time series (single mode)
  constant_vs_oscillating_crh_comparison.pdf / .png       24-h comparison (compare mode)
  constant_vs_oscillating_crh_comparison_zoom.pdf / .png  6-h zoom (compare mode)

Usage:
    python model/analysis/crh_oscillatory/plot_crh.py constant
    python model/analysis/crh_oscillatory/plot_crh.py single
    python model/analysis/crh_oscillatory/plot_crh.py compare [period_min] [amplitude_frac]

Examples:
    python model/analysis/crh_oscillatory/plot_crh.py constant
    python model/analysis/crh_oscillatory/plot_crh.py single
    python model/analysis/crh_oscillatory/plot_crh.py compare 60 0.5
    python model/analysis/crh_oscillatory/plot_crh.py compare 45 0.3
"""

import sys
import math
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from matplotlib import gridspec
from pathlib import Path

plt.rcParams.update({'font.size': 18})

# ── path setup ─────────────────────────────────────────────────────────────────
_SCRIPT_DIR = Path(__file__).resolve().parent
_SIM_CONST  = _SCRIPT_DIR / 'output' / 'simulations' / 'const'
_SIM_OSC    = _SCRIPT_DIR / 'output' / 'simulations' / 'oscillating'
_FIG_DIR    = _SCRIPT_DIR / 'output' / 'figures'
_FIG_DIR.mkdir(parents=True, exist_ok=True)

# ── argument parsing ───────────────────────────────────────────────────────────
if len(sys.argv) < 2:
    print(__doc__)
    sys.exit(1)

mode = sys.argv[1].lower()

OCC_CONDITIONS = {
    "High Oscillating CRH":   "high_osc_crh.npy",
    "Medium Oscillating CRH": "medium_osc_crh.npy",
    "Low Oscillating CRH":    "low_osc_crh.npy",
}

# ── constant CRH plots (Figure 4B) ─────────────────────────────────────────────────────
if mode == 'constant':
    print('Generating constant CRH plots (Figure 4B)...')

    NUM_DAYS  = 40
    TIMESTEPS = 1440 * NUM_DAYS
    x_axis    = np.arange(1440)  # last 24 h

    CONST_CONDITIONS = [
        ('High CRH',   'high_crh.npy'),
        ('Medium CRH', 'medium_crh.npy'),
        ('Low CRH',    'low_crh.npy'),
    ]

    fig  = plt.figure(figsize=(12, 10))
    grid = gridspec.GridSpec(3, 1, figure=fig, hspace=0.5)

    t0 = datetime.strptime('09:00:00', '%H:%M:%S')
    for i, (title, filename) in enumerate(CONST_CONDITIONS):
        data = np.load(str(_SIM_CONST / filename))
        ax1  = fig.add_subplot(grid[i])
        ax2  = ax1.twinx()
        ax1.plot(x_axis, data[-1440:, 0], color='blue', lw=2)
        ax2.plot(x_axis, data[-1440:, 1], color='red',  lw=2)
        ax1.set_ylabel('ACTH (pmol/L)', color='blue')
        ax2.set_ylabel('CORT (nmol/L)', color='red')
        ax1.set_ylim([0, 15])
        ax2.set_ylim([1, 1100])
        ax1.set_title(title)
        if i < 2:
            ax1.set_xticklabels([])
        else:
            ax1.set_xticks([i for i in range(180, 1440, 360)])
            ax1.set_xticklabels([(t0 + timedelta(minutes=i)).strftime('%H:%M')
                                  for i in range(180, 1440, 360)])
            ax1.set_xlabel('Time of day')

    plt.tight_layout()
    for ext in ('pdf', 'png'):
        plt.savefig(str(_FIG_DIR / f'constant_crh_conditions.{ext}'),
                    bbox_inches='tight', dpi=300 if ext == 'png' else None)
    plt.close()
    print('  Saved: constant_crh_conditions')
    print('\n✓ Constant CRH plots complete!')

# ── single oscillating plots ─────────────────────────────────────────────────────
elif mode == 'single':
    print("Generating oscillating CRH plots (single)...")

    NUM_DAYS   = 10
    TIMESTEPS  = 1440 * NUM_DAYS
    times      = np.linspace(0, TIMESTEPS, TIMESTEPS)
    x_axis     = [x - 1440 * (NUM_DAYS - 1) for x in times[((NUM_DAYS - 1) * 1440):]]

    # — last 24 hours —
    fig  = plt.figure(figsize=(12, 10))
    grid = gridspec.GridSpec(3, 1, figure=fig, hspace=0.5)

    for i, (title, filename) in enumerate(OCC_CONDITIONS.items()):
        data = np.load(str(_SIM_OSC / filename))
        ax1  = fig.add_subplot(grid[i])
        ax2  = ax1.twinx()
        ax1.plot(x_axis, data[-1440:, 0], color='blue',  lw=2)
        ax2.plot(x_axis, data[-1440:, 1], color='red',   lw=2)
        ax1.set_ylabel('ACTH (pmol/L)', color='blue')
        ax2.set_ylabel('CORT (nmol/L)', color='red')
        ax1.set_ylim([0, 15])
        ax2.set_ylim([1, 1100])
        ax1.set_title(title)
        if i < 2:
            ax1.set_xticklabels([])
            ax2.set_xticklabels([])
        else:
            t0 = datetime.strptime('09:00:00', "%H:%M:%S")
            ax1.set_xticks([i for i in range(180, 1440, 360)])
            ax1.set_xticklabels([(t0 + timedelta(minutes=i)).strftime("%H:%M")
                                  for i in range(180, 1440, 360)])
            ax1.set_xlabel('Time')

    plt.tight_layout()
    for ext in ('pdf', 'png'):
        plt.savefig(str(_FIG_DIR / f'oscillating_crh_conditions.{ext}'),
                    bbox_inches='tight', dpi=300 if ext == 'png' else None)
    plt.close()
    print("  Saved: oscillating_crh_conditions")

    # — full time series —
    fig_full  = plt.figure(figsize=(12, 10))
    grid_full = gridspec.GridSpec(3, 1, figure=fig_full, hspace=0.5)

    for i, (title, filename) in enumerate(OCC_CONDITIONS.items()):
        data         = np.load(str(_SIM_OSC / filename))
        total_min    = data.shape[0]
        x_full       = np.arange(total_min)
        ax1 = fig_full.add_subplot(grid_full[i])
        ax2 = ax1.twinx()
        ax1.plot(x_full, data[:, 0], color='blue', lw=1.5)
        ax2.plot(x_full, data[:, 1], color='red',  lw=1.5)
        ax1.set_ylabel('ACTH (pmol/L)', color='blue')
        ax2.set_ylabel('CORT (nmol/L)', color='red')
        ax1.set_ylim([0, 15])
        ax2.set_ylim([1, 1100])
        ax1.set_title(title)
        if i < 2:
            ax1.set_xticklabels([])
            ax2.set_xticklabels([])
        else:
            n_days    = max(1, total_min // 1440)
            day_marks = [d * 1440 for d in range(n_days + 1)]
            ax1.set_xticks(day_marks)
            ax1.set_xticklabels([f"Day {d}" for d in range(len(day_marks))])
            ax1.set_xlabel('Time')

    plt.tight_layout()
    for ext in ('pdf', 'png'):
        plt.savefig(str(_FIG_DIR / f'oscillating_crh_conditions_full.{ext}'),
                    bbox_inches='tight', dpi=300 if ext == 'png' else None)
    plt.close()
    print("  Saved: oscillating_crh_conditions_full")
    print("\n✓ Single plots complete!")

# ── comparison plots ───────────────────────────────────────────────────────────
elif mode == 'compare':
    T_ultradian        = float(sys.argv[2]) if len(sys.argv) > 2 else 60
    amplitude_fraction = float(sys.argv[3]) if len(sys.argv) > 3 else 0.5

    print(f"Generating comparison plots (period={T_ultradian} min, "
          f"amplitude={amplitude_fraction}× baseline)...")

    conditions       = ["Low", "Medium", "High"]
    const_files      = ["low_crh.npy",    "medium_crh.npy",    "high_crh.npy"]
    osc_files        = ["low_osc_crh.npy", "medium_osc_crh.npy", "high_osc_crh.npy"]
    const_crh_values = [0.1, 10, 10000]
    osc_crh_params   = [(v, v * amplitude_fraction) for v in const_crh_values]
    omega            = 2 * math.pi / T_ultradian

    def _draw_comparison(hours, suffix):
        minutes     = hours * 60
        x_axis      = np.arange(minutes)
        fig         = plt.figure(figsize=(20, 12))
        grid        = gridspec.GridSpec(3, 2, figure=fig, hspace=0.4, wspace=0.5)

        for row, (cond, cf, of, const_crh, (baseline, amp)) in enumerate(
                zip(conditions, const_files, osc_files, const_crh_values, osc_crh_params)):

            const_data = np.load(str(_SIM_CONST / cf))
            osc_data   = np.load(str(_SIM_OSC / of))

            crh_min = min(const_crh, baseline - amp) * 0.95
            crh_max = max(const_crh, baseline + amp) * 1.05

            const_crh_trace = np.full(minutes, const_crh)
            time_offset     = len(osc_data) - minutes
            osc_crh_trace   = baseline + amp * np.cos(omega * (x_axis + time_offset))

            for col, (data, crh_trace, col_title) in enumerate([
                (const_data, const_crh_trace, 'Constant CRH'),
                (osc_data,   osc_crh_trace,   f'Oscillating CRH ({T_ultradian:.0f} min period)'),
            ]):
                ax1 = fig.add_subplot(grid[row, col])
                ax2 = ax1.twinx()
                ax3 = ax1.twinx()
                ax3.spines['right'].set_position(('outward', 90))

                ax1.plot(x_axis, data[-minutes:, 0], color='blue', lw=2, zorder=3)
                ax2.plot(x_axis, data[-minutes:, 1], color='red',  lw=2, zorder=3)
                ax3.plot(x_axis, crh_trace,           color='lightgrey', lw=2, alpha=0.7, zorder=1)

                ax1.set_ylabel('ACTH (pmol/L)', color='blue', fontsize=16)
                ax2.set_ylabel('CORT (nmol/L)', color='red',  fontsize=16)
                ax3.set_ylabel('CRH (AU)',       color='grey', fontsize=14)
                ax1.set_ylim([0, 15])
                ax2.set_ylim([1, 1100])
                ax3.set_ylim([crh_min, crh_max])
                ax3.tick_params(axis='y', labelcolor='grey', labelsize=12)

                if row == 0:
                    ax1.set_title(col_title, fontsize=20, fontweight='bold')

                ax1.text(0.02, 0.95, f'{cond} CRH', transform=ax1.transAxes,
                         fontsize=16, verticalalignment='top',
                         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

                if row < 2:
                    ax1.set_xticklabels([])
                else:
                    t0 = datetime.strptime('09:00:00', "%H:%M:%S")
                    if hours == 24:
                        ticks = range(180, minutes, 360)
                    else:
                        ticks = [i * 60 for i in range(hours + 1)]
                    ax1.set_xticks(list(ticks))
                    ax1.set_xticklabels([(t0 + timedelta(minutes=i)).strftime("%H:%M")
                                         for i in ticks], fontsize=12)
                    ax1.set_xlabel('Time', fontsize=16)

        plt.suptitle(f'Amplitude: {amplitude_fraction}\u00d7 baseline',
                     fontsize=22, fontweight='bold', y=0.995)
        fname = f'constant_vs_oscillating_crh_comparison{suffix}'
        for ext in ('pdf', 'png'):
            plt.savefig(str(_FIG_DIR / f'{fname}.{ext}'),
                        bbox_inches='tight', dpi=300 if ext == 'png' else None)
        plt.close()
        print(f"  Saved: {fname}")

    _draw_comparison(24, '')
    _draw_comparison(6,  '_zoom')
    print("\nComparison plots complete!")

else:
    print(f"Error: Unknown mode '{mode}'. Use 'single' or 'compare'.")
    sys.exit(1)
