"""
Unified CRH simulation script.
Runs either constant or oscillating CRH simulations and saves results as .npy files
for use by plot_crh.py or grid_crh_analysis.py.

CRH drive model:  Φ(t) = λ_a · exp(λ_s · cos(...))
An oscillating variant replaces the circadian modulation with a cosine at a
user-specified ultradian period.

Manuscript figures generated by this script
--------------------------------------------
  Figure 4B  — Low, Medium and High constant CRH simulations.
               Run this first, then plot with plot_crh.py:
                   python model/analysis/crh_oscillatory/simulate_crh.py constant
                   python model/analysis/crh_oscillatory/plot_crh.py constant
               Outputs: model/analysis/crh_oscillatory/output/simulations/const/{high,medium,low}_crh.npy

Usage:
    python model/analysis/crh_oscillatory/simulate_crh.py constant
    python model/analysis/crh_oscillatory/simulate_crh.py oscillating [period_min] [amplitude_frac]

Examples:
    python model/analysis/crh_oscillatory/simulate_crh.py constant
    python model/analysis/crh_oscillatory/simulate_crh.py oscillating 60 0.5
    python model/analysis/crh_oscillatory/simulate_crh.py oscillating 45 0.3
"""

import sys
import os
import math
import json
import numpy as np
from pathlib import Path

# ── path setup ─────────────────────────────────────────────────────────────────
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT  = _SCRIPT_DIR.parents[2]          # HPAAxisModel/
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from model.code.classes.model_class import Model  # noqa: E402

# ── argument parsing ───────────────────────────────────────────────────────────
if len(sys.argv) < 2:
    print(__doc__)
    sys.exit(1)

mode = sys.argv[1].lower()

# ── simulation constants ───────────────────────────────────────────────────────
NUM_DAYS   = 40
TIMESTEPS  = 1440 * NUM_DAYS
TIMES      = np.linspace(0, TIMESTEPS, TIMESTEPS)
SIGNAL     = 'both'
REJECT     = False

# CRH baseline conditions (AU)
CRH_CONDITIONS = {
    "High CRH":   ("high_crh.npy",   10000),
    "Medium CRH": ("medium_crh.npy", 10),
    "Low CRH":    ("low_crh.npy",    0.1),
}

# ── load base configuration ────────────────────────────────────────────────────
config_path = _REPO_ROOT / 'model' / 'config' / 'base' / 'mean_parameters.json'
with open(config_path, 'r') as f:
    base_config = json.load(f)

fixed_params = base_config.get('fixed_params', {})
parameters   = base_config.get('parameters', {})


# ── helpers ────────────────────────────────────────────────────────────────────
class ModelOscillatingCRH(Model):
    """Model subclass that replaces the circadian CRH drive with an ultradian cosine."""

    def __init__(self, baseline_crh, osc_amplitude, osc_period, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.baseline_crh      = baseline_crh
        self.osc_amplitude     = osc_amplitude
        self.omega_ultradian   = 2 * math.pi / osc_period

    def crh(self, t, t_s=None, lambda_a=None, lambda_s=None, sigma=None, T_c=1440):
        crh_value = self.baseline_crh + self.osc_amplitude * math.cos(self.omega_ultradian * t)
        if self.stressor_object is not None:
            if self.stressor_type == 'HS':
                crh_value += self.stressor_object.stressor_heart_surgery(t)
            else:
                crh_value += self.stressor_object.stressor(t)
        return crh_value


def _simulate(model_instance):
    param_set = model_instance.suggested_parameters()
    result    = model_instance.simulate(param_set, TIMES)
    if result.ndim == 1:
        result = result[:, np.newaxis]
    return result


# ── constant CRH mode ──────────────────────────────────────────────────────────
if mode == 'constant':
    print("Running constant CRH simulations...")
    out_dir = _SCRIPT_DIR / 'output' / 'simulations' / 'const'
    out_dir.mkdir(parents=True, exist_ok=True)

    for label, (filename, lambda_a_val) in CRH_CONDITIONS.items():
        params = dict(parameters)
        params['lambda_a'] = lambda_a_val
        params['lambda_s'] = 0

        dde_model = Model(
            fixed_params=fixed_params,
            suggested_params=params,
            signal=SIGNAL,
            num_days=1,
            reject=REJECT,
            length_model=TIMESTEPS,
        )
        result = _simulate(dde_model)
        np.save(str(out_dir / filename), result)
        print(f"  Saved: {label} → {filename}")

    print(f"\n✓ Constant CRH simulations complete. Results in {out_dir}/")

# ── oscillating CRH mode ───────────────────────────────────────────────────────
elif mode == 'oscillating':
    T_ultradian       = float(sys.argv[2]) if len(sys.argv) > 2 else 60
    amplitude_fraction = float(sys.argv[3]) if len(sys.argv) > 3 else 0.5

    print(f"Running oscillating CRH simulations...")
    print(f"  Period:    {T_ultradian} minutes")
    print(f"  Amplitude: {amplitude_fraction}× baseline")

    out_dir = _SCRIPT_DIR / 'output' / 'simulations' / 'oscillating'
    out_dir.mkdir(parents=True, exist_ok=True)

    osc_conditions = {
        "High Oscillating CRH":   ("high_osc_crh.npy",   10000, 10000 * amplitude_fraction),
        "Medium Oscillating CRH": ("medium_osc_crh.npy", 10,    10    * amplitude_fraction),
        "Low Oscillating CRH":    ("low_osc_crh.npy",    0.1,   0.1   * amplitude_fraction),
    }

    params_base = dict(parameters)
    params_base['lambda_s'] = 0

    for label, (filename, baseline_crh, osc_amplitude) in osc_conditions.items():
        dde_model = ModelOscillatingCRH(
            baseline_crh=baseline_crh,
            osc_amplitude=osc_amplitude,
            osc_period=T_ultradian,
            fixed_params=fixed_params,
            suggested_params=dict(params_base),
            signal=SIGNAL,
            num_days=1,
            reject=REJECT,
            length_model=TIMESTEPS,
        )
        result = _simulate(dde_model)
        np.save(str(out_dir / filename), result)
        print(f"  Saved: {label} → {filename}")

    print(f"\n✓ Oscillating CRH simulations complete. Results in {out_dir}/")

else:
    print(f"Error: Unknown mode '{mode}'. Use 'constant' or 'oscillating'.")
    sys.exit(1)
