"""
HPA Axis Data Visualisation
============================
Generates descriptive plots of the raw hormone time series (Cortisol and ACTH)
for all participants.

Manuscript figures generated by this script
--------------------------------------------
  Figure 2A  — Raw ACTH & Cortisol time series (shared x-axis, all participants)
               Saved: data_analysis/output/data_plots/data_acth_cort_raw_unsmoothed.pdf
               Saved: data_analysis/output/data_plots/data_acth_cort_raw_unsmoothed.png

  Figure 2B  — Cross-correlation (time-lag) between ACTH and Cortisol
               Saved: data_analysis/output/data_plots/timelag.pdf
               Saved: data_analysis/output/data_plots/timelag.png

Key settings
------------
raw_data_dir : 'data_analysis/data/raw'   (raw participant CSVs)
font.size    : 24                         (all plots)

Usage:
    python data_analysis/code/data_plots.py
"""

import matplotlib.pyplot as plt
import os
import pandas as pd
from scipy.stats import zscore
from scipy.signal import correlate
import numpy as np
import matplotlib.dates as mdates
import seaborn as sns

# ---- Load raw participant data ----
raw_data_dir = 'data_analysis/data/raw'
raw_dfs = []
for filename in sorted(os.listdir(raw_data_dir)):
    if filename.endswith(".csv") and filename.startswith("participant_"):
        pid = int(filename.split('participant_')[1].split('.csv')[0])
        df = pd.read_csv(os.path.join(raw_data_dir, filename))
        df = df[['Date', 'Time', 'Cortisol', 'ACTH']].copy()
        df['datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%d/%m/%Y %H:%M:%S', errors='coerce')
        df = df.dropna(subset=['datetime', 'Cortisol', 'ACTH'])
        df['participant_id'] = pid
        if pid > 7:
            df['ACTH'] = df['ACTH'] / 4.54113
        raw_dfs.append(df)

raw_combined = pd.concat(raw_dfs, ignore_index=True)
raw_combined = raw_combined.sort_values(['participant_id', 'datetime'])

plt.rcParams.update({"font.size": 24})

output_dir = "data_analysis/output/data_plots"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# ---- Standalone ACTH plot ----
plt.figure(figsize=(9, 4))
ax1 = plt.gca()
for pid, group in raw_combined.groupby('participant_id'):
    ax1.plot(group['datetime'], group['ACTH'], marker='o', markersize=3, linestyle='--', alpha=0.7)
ax1.set_ylabel("ACTH (pmol/L)")
ax1.set_xlabel("Clock time (hrs)")
ax1.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
ax1.xaxis.set_major_locator(mdates.HourLocator(interval=6))
plt.tight_layout()
plt.savefig(f"{output_dir}/data_acth_raw_unsmoothed.pdf", dpi=300, bbox_inches="tight")
plt.savefig(f"{output_dir}/data_acth_raw_unsmoothed.png", dpi=300, bbox_inches="tight")
plt.show()
plt.close()

# ---- Combined ACTH & Cortisol plot (shared x-axis) ----
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 8), sharex=True)

for pid, group in raw_combined.groupby('participant_id'):
    ax1.plot(group['datetime'], group['ACTH'], marker='o', markersize=3, linestyle='--', alpha=0.7)
ax1.set_ylabel("ACTH (pmol/L)")
ax1.yaxis.set_label_coords(-0.1, 0.5)

for pid, group in raw_combined.groupby('participant_id'):
    ax2.plot(group['datetime'], group['Cortisol'], marker='o', markersize=3, linestyle='--', alpha=0.7)
ax2.set_ylabel("CORT (nmol/L)")
ax2.set_xlabel("Clock time (hrs)")
ax2.yaxis.set_label_coords(-0.1, 0.5)

ax2.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
ax2.xaxis.set_major_locator(mdates.HourLocator(interval=6))

plt.tight_layout()
plt.savefig(f"{output_dir}/data_acth_cort_raw_unsmoothed.pdf", dpi=300, bbox_inches="tight")
plt.savefig(f"{output_dir}/data_acth_cort_raw_unsmoothed.png", dpi=300, bbox_inches="tight")
plt.show()
plt.close()
print("Created raw ACTH & CORT plots.")

# ---- Load shifted data for time-lag correlation ----
data_dir = 'model/data'
acth_data = pd.read_csv(f'{data_dir}/data_shifted_ACTH_1min_09_00.csv')
cort_data = pd.read_csv(f'{data_dir}/data_shifted_Cortisol_1min_09_00.csv')
acth_data["x"] = pd.to_datetime(acth_data["x"], errors="coerce")
cort_data["x"] = pd.to_datetime(cort_data["x"], errors="coerce")
acth_data["test"] = acth_data["test"].astype(int)
cort_data["test"] = cort_data["test"].astype(int)
cort_data = cort_data.sort_values(by=["test", "x"])
acth_data = acth_data.sort_values(by=["test", "x"])
merged_data = pd.merge(acth_data, cort_data, on=["x", "test"], suffixes=("_acth", "_cort"))

# 3. Plot Time-lag Correlation
plt.figure(figsize=(12, 4))
ax3 = plt.gca()
correlations = []
time_lags = []

for participant, group in merged_data.groupby("test"):
    acth_values = group["y_acth"].values
    cort_values = group["y_cort"].values
    lag_min, lag_max = -250, 250
    correlation = correlate(acth_values - np.mean(acth_values), cort_values - np.mean(cort_values), mode="full")
    correlation /= np.max(correlation)  # Normalize
    lags = np.arange(-len(acth_values) + 1, len(acth_values))
    valid_indices = (lags >= lag_min) & (lags <= lag_max)
    lags_filtered = lags[valid_indices]
    correlation_filtered = correlation[valid_indices]
    correlations.append(correlation)
    peak_lag = lags_filtered[np.argmax(correlation_filtered)]
    time_lags.append(peak_lag)


    ax3.plot(lags_filtered, correlation_filtered, label=f"Participant {participant}", alpha=0.7)

mean_lag = np.mean(time_lags)
std_lag = np.std(time_lags)

ax3.axvline(mean_lag, color="red", linestyle="--", linewidth=1.5, label=f"Mean lag = {mean_lag:.2f} ± {std_lag:.2f}")

#ax3.text(mean_lag + 5, 0.9, f"{mean_lag:.1f} ± {std_lag:.1f}", color="red", fontsize=10)
ax3.set_xlabel("Lag (min)")
ax3.set_ylabel("Correlation")
ax3.grid(True, linestyle="--", alpha=0.5)
plt.savefig(f"{output_dir}/timelag.pdf", dpi=300, bbox_inches="tight")
plt.savefig(f"{output_dir}/timelag.png", dpi=300, bbox_inches="tight")
plt.show()
plt.close()

time_lags = np.array(time_lags)
mean_lag = np.mean(time_lags)
std_lag = np.std(time_lags)
min_lag = np.min(time_lags)
max_lag = np.max(time_lags)


