"""
HPA Axis Supplementary Data Plots

Generates Figure S1 of the manuscript: individual hormone profiles and cross-correlations
for all ten participants.

Manuscript figures generated by this script
--------------------------------------------
  Figure S1A — Raw 24-hour plasma ACTH (blue) and CORT (red) concentrations for each of
               the ten healthy participants; one row per participant, participant number
               labelled on the left y-axis.

  Figure S1B — Corresponding z-scored ACTH and CORT signals used for cross-correlation
               analysis; same row layout as S1A.

  Figure S1C — Time-lagged cross-correlation functions between ACTH and CORT, showing
               negative lag values at the peak correlation, consistent with a temporal
               delay between ACTH and CORT; one row per participant.

               All three panels are plotted together as a single 10×3 grid figure.
               Saved: data_analysis/output/data_plots/data_supp.pdf
               Saved: data_analysis/output/data_plots/data_supp.png

Usage:
    python data_analysis/code/data_supp.py      
    
Input:
    - data_analysis/data/data_shifted_ACTH_1min_09_00.csv
    - data_analysis/data/data_shifted_Cortisol_1min_09_00.csv
"""

import os
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import zscore
from scipy.signal import correlate
import numpy as np
import matplotlib.dates as mdates

# Where is the data?
data_dir = 'data_analysis/data'
acth_data_file = 'data_shifted_ACTH_1min_09_00.csv'
cort_data_file = 'data_shifted_Cortisol_1min_09_00.csv'

output_dir = 'data_analysis/output/data_plots'
os.makedirs(output_dir, exist_ok=True)

# Get the raw data
acth_data = pd.read_csv(f'{data_dir}/{acth_data_file}')
cort_data = pd.read_csv(f'{data_dir}/{cort_data_file}')
acth_data["x"] = pd.to_datetime(acth_data["x"], errors="coerce")
cort_data["x"] = pd.to_datetime(cort_data["x"], errors="coerce")
acth_data["test"] = acth_data["test"].astype(int)
cort_data["test"] = cort_data["test"].astype(int)
cort_data = cort_data.sort_values(by=["test", "x"])
acth_data = acth_data.sort_values(by=["test", "x"])


def plot_participants(acth_data, cort_data):

    # Merge data on x (datetime) and test (participant)
    merged_data = pd.merge(acth_data, cort_data, on=["x", "test"], suffixes=("_acth", "_cort"))
    # Get unique participants (tests)
    participants = merged_data["test"].unique()
    num_participants = len(participants)

    # Calculate global y-axis limits
    y_raw_min_acth = merged_data["y_acth"].min()
    y_raw_max_acth = merged_data["y_acth"].max()
    y_raw_min_cort = merged_data["y_cort"].min()
    y_raw_max_cort = merged_data["y_cort"].max()
    y_z_min = -3  # Standard z-scores typically range from -3 to 3
    y_z_max = 3
    xcorr_min = -1  # Normalized cross-correlation values range from -1 to 1
    xcorr_max = 1

    # Create figure and axes
    fig, axes = plt.subplots(num_participants, 3, figsize=(15, 5 * num_participants), constrained_layout=True)

    # Add column headings
    column_titles = ["A) Raw data", "B) Z-Scores", "C) Cross-correlation"]
    for col_idx, title in enumerate(column_titles):
        axes[0, col_idx].set_title(title, fontsize=14, fontweight="bold")

    mid_idx = num_participants // 2
    for i, participant in enumerate(participants):
        participant_data = merged_data[merged_data["test"] == participant]

        ax1 = axes[i, 0]
        ax1.plot(participant_data["x"], participant_data["y_acth"], color="blue", alpha=0.7, label="ACTH")
        ax1.set_ylabel("")
        ax1.tick_params(axis="y", labelcolor="blue")
        ax1.set_ylim(y_raw_min_acth, y_raw_max_acth)

        # Annotate participant label just outside the left y-axis, vertically centered
        ax1.annotate(f"{participant}",
                xy=(0, 0.5), xycoords=('axes fraction', 'axes fraction'),
                xytext=(-55, 0), textcoords='offset points',
                va='center', ha='right', fontsize=10, color='black')

        ax1_cort = ax1.twinx()
        ax1_cort.plot(participant_data["x"], participant_data["y_cort"], color="red", alpha=0.7, label="CORT")
        ax1_cort.tick_params(axis="y", labelcolor="red")
        ax1_cort.set_ylim(y_raw_min_cort, y_raw_max_cort)
        ax1.grid(True, linestyle="--", alpha=0.5)

        # Only set ACTH/CORT y-axis headings for the middle row
        if i == mid_idx:
            ax1.set_ylabel("ACTH (nmol/L)", fontsize=12, fontweight="bold", color="blue")
            ax1_cort.set_ylabel("CORT (nmol/L)", fontsize=12, fontweight="bold", color="red")

        ax2 = axes[i, 1]
        participant_data = participant_data.copy()
        participant_data["z_score_acth"] = zscore(participant_data["y_acth"])
        participant_data["z_score_cort"] = zscore(participant_data["y_cort"])
        ax2.plot(participant_data["x"], participant_data["z_score_acth"], color="blue", alpha=0.7)
        ax2.set_ylim(y_z_min, y_z_max)
        ax2_cort = ax2.twinx()
        ax2_cort.plot(participant_data["x"], participant_data["z_score_cort"], color="red", alpha=0.7)
        ax2_cort.set_ylim(y_z_min, y_z_max)
        ax2.grid(True, linestyle="--", alpha=0.5)

        ax3 = axes[i, 2]
        acth_values = participant_data["y_acth"].values
        cort_values = participant_data["y_cort"].values
        lags = np.arange(-len(acth_values) + 1, len(acth_values))
        correlation = correlate(acth_values - np.mean(acth_values), cort_values - np.mean(cort_values), mode='full')
        correlation /= np.max(correlation)  # Normalize

        ax3.plot(lags, correlation, color="purple", alpha=0.7)
        ax3.axhline(0, color="black", linestyle="--", linewidth=0.8, alpha=0.7)
        ax3.set_ylim(xcorr_min, xcorr_max)
        ax3.grid(True, linestyle="--", alpha=0.5)
        if i == num_participants - 1:
            ax3.set_xlabel("Lag (minutes)")

        if i < num_participants - 1:
            for ax in axes[i, :3]:
                ax.set_xticklabels([])
        else:
            for ax in axes[i, :3]:
                ax.set_xlabel("Time")

        for ax in axes[i, :2]:
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
            ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))
            if i < num_participants - 1:
                ax.set_xticklabels([])
            else:
                ax.set_xlabel("Time (minutes)")

    fig.set_size_inches(13, 10)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/data_supp.png', dpi=300, bbox_inches="tight")
    plt.savefig(f'{output_dir}/data_supp.pdf', dpi=300, bbox_inches="tight")
    plt.show()


plot_participants(acth_data, cort_data)
