"""Stressor Timing Selection — Figure S6A

Runs a single-day baseline (no stressor) simulation, identifies ultradian
troughs/peaks in the resulting CORT signal, and marks the selected stressor
timings as green dashed vertical lines relative to the model's circadian CRH
drive (black) and the baseline cortisol output (red).

This script is fully self-contained: it derives stressor timing points from
a fresh simulation rather than requiring pre-existing simulation output,
breaking the circular dependency between points_to_consider.json and the
simulation sweep.

Manuscript figures generated by this script
--------------------------------------------
  Figure S6A — Selected stressor timings (green dashed lines) shown relative to the
               model's circadian CRH drive (black) and the ultradian phases in the
               baseline cortisol output (red).
               Saved: stressors/output/stressor_fig.pdf
               Saved: stressors/output/stressor_fig.png

Usage:
    cd stressors/stressor_analysis
    python get_stressor_times.py
    python get_stressor_times.py --config model/config/base/mean_parameters.json
    python get_stressor_times.py --config model/config/base/mean_parameters.json --num-days 4
"""

import sys
import os

# Allow imports from the repo root (model package lives there).
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, '../..'))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

import numpy as np
import matplotlib.pyplot as plt
import json
import argparse
from scipy.signal import find_peaks
from model.code.classes.model_class import Model


def find_peaks_and_throughs(signal):
    peaks, _ = find_peaks(signal, height=None, distance=None)
    troughs, _ = find_peaks(-signal, height=None, distance=None)
    return peaks, troughs


def calculate_ultradian_period(signal, time_array):
    peaks, _ = find_peaks(signal, height=None, distance=None)
    peak_times = time_array[peaks]
    periods = np.diff(peak_times)
    return np.mean(periods)


# Calculate phase of signal ultradian rhythm
def calculate_phase(signal, point_time, time_ref):
    phase_length = len(signal)
    phase_radians = ((point_time - time_ref) / phase_length) * 2 * np.pi
    return phase_radians


# ---------------------------------------------------------------------------
# Parse command-line arguments
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description='Determine stressor timing points from a baseline simulation')
parser.add_argument(
    '--config', type=str,
    default=os.path.join(_REPO_ROOT, 'model/config/base/mean_parameters.json'),
    help='Path to model parameter config JSON (default: mean_parameters.json)',
)
parser.add_argument(
    '--num-days', type=int, default=4,
    help='Number of days to simulate for spin-up before analysing the final day (default: 4)',
)
parser.add_argument(
    '--selected-throughs', type=int, nargs='+', default=[1, 4, 6, 7],
    help='Indices into the troughs array to use as stressor timing anchor points (default: 1 4 6 7)',
)
parser.add_argument('--scenario', type=str, default='ACUTE',
                    help='Scenario label (informational only; default: ACUTE)')
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Load model config and run a BASELINE (no stressor) simulation
# ---------------------------------------------------------------------------
print('################')
print('Loading model config and running baseline simulation')

with open(args.config) as f:
    config = json.load(f)

parameters = config['parameters']
fixed_params = config.get('fixed_params', {})
num_days = args.num_days
length_model = 1440  # one day in minutes

dde_model = Model(
    fixed_params=fixed_params,
    suggested_params=parameters,
    signal='Both',
    num_days=num_days,
    reject=False,
    stressor_parameters={},   # no stressor — pure baseline
    length_model=length_model,
    days_to_keep=1,           # keep only the final day
)

timesteps = length_model * num_days
times_full = np.linspace(0, timesteps, timesteps)
param_values = dde_model.suggested_parameters()

print(f'Simulating {num_days} days ({timesteps} minutes) …')
result = dde_model.simulate(param_values, times_full)
# result is the last 1440 minutes (days_to_keep=1)
signal = result[:, 1]  # cortisol column

# CRH is periodic with T=1440, so we can evaluate it over [0, 1440) directly.
times_chopped = np.arange(0, 1440)
crh_values = np.array([dde_model.crh(float(t)) for t in times_chopped])

print(f'################')
print(f'Find peaks and troughs')
print(f'Signal length {len(signal)}')
signal_chopped = signal[0:1440]
peaks, troughs = find_peaks_and_throughs(signal_chopped)
print(f'Peaks: {peaks.tolist()}')
print(f'Troughs: {troughs.tolist()}')

plt.plot(times_chopped, signal_chopped, 'b-')
for peak in peaks:
    plt.plot(times_chopped[peak], signal_chopped[peak], 'ro')

for trough in troughs:
    plt.plot(times_chopped[trough], signal_chopped[trough], 'go')

plt.grid()
plt.show()

# Troughs we're interested in (configurable via --selected-throughs):
selected_throughs = args.selected_throughs

ultradian_period = calculate_ultradian_period(signal_chopped, times_chopped)
print(f'Ultradian period is: {ultradian_period}')

fig, ax1 = plt.subplots(figsize=(8, 4), constrained_layout=True)
ax1.plot(times_chopped, signal_chopped, 'r-', label='Cortisol')

points_dictionary = []

for i in range(len(selected_throughs)):
    through_idx = selected_throughs[i]
    if through_idx >= len(troughs):
        print(f'Warning: selected_throughs index {through_idx} out of range '
              f'({len(troughs)} troughs found); skipping.')
        continue
    through = troughs[through_idx]
    # Use next trough if it exists, otherwise fall back to end of window
    if through_idx + 1 < len(troughs):
        follow_through = troughs[through_idx + 1]
    else:
        follow_through = len(signal_chopped) - 1
    # Guard in case indices are equal or reversed
    if follow_through <= through:
        follow_through = min(len(signal_chopped) - 1, through + 1)

    points_dictionary.append({'ultradian_points': []})

    # First peak after the selected trough
    find_peak = None
    for peak in peaks:
        if peak > through:
            find_peak = peak
            break
    if find_peak is None:
        print(f'Warning: no peak found after trough index {through_idx}; skipping.')
        points_dictionary.pop()
        continue

    midpoint = ((find_peak - through) // 2) + through
    midpoint_falling = ((follow_through - find_peak) // 2) + find_peak

    points_dictionary[-1]['ultradian_points'].append({'timing': int(find_peak), 'phase': float(np.pi), 'describe': 'peak'})
    ax1.plot([find_peak, find_peak], [0, signal[find_peak]], color='g', linestyle='--')

    points_dictionary[-1]['ultradian_points'].append({'timing': int(midpoint), 'phase': float(np.pi / 2), 'describe': 'midpoint_rising'})
    ax1.plot([midpoint, midpoint], [0, signal[midpoint]], color='g', linestyle='--')

    points_dictionary[-1]['ultradian_points'].append({'timing': int(through), 'phase': 0, 'describe': 'through'})
    ax1.plot([through, through], [0, signal[through]], color='g', linestyle='--')

    points_dictionary[-1]['ultradian_points'].append({'timing': int(midpoint_falling), 'phase': float(3 * np.pi / 2), 'describe': 'midpoint_falling'})
    ax1.plot([midpoint_falling, midpoint_falling], [0, signal[midpoint_falling]], color='g', linestyle='--')

ax1.set_ylim(0, None)

with open(os.path.join(_SCRIPT_DIR, "points_to_consider.json"), "w") as outfile:
    json.dump(points_dictionary, outfile, indent=2)

print(f'Saved {len(points_dictionary)} ultradian cycles to points_to_consider.json')
for entry in points_dictionary:
    for pt in entry['ultradian_points']:
        print(f'  timing={pt["timing"]:4d}  phase={pt["describe"]}')

ax2 = ax1.twinx()
ax2.plot(times_chopped, crh_values, label='CRH Drive', color='black')
ax2.set_ylabel('CRH Drive')
ax1.set_xlabel('Time (minutes)')
ax1.set_ylabel('Cortisol')

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
fig.legend(lines1 + lines2, labels1 + labels2, loc='upper center', bbox_to_anchor=(0.5, 1), ncol=2, fontsize='small', frameon=False)

plt.savefig(os.path.join(_SCRIPT_DIR, '../output/stressor_fig.pdf'))
plt.savefig(os.path.join(_SCRIPT_DIR, '../output/stressor_fig.png'))

plt.show()
 



'''
def extract_phases(signal, time_array, ultradian_period, circadian_period=1440):
    ultradian_phase = (2 * np.pi * (time_array % ultradian_period) / ultradian_period) % (2 * np.pi)
    circadian_phase = (2 * np.pi * (time_array % circadian_period) / circadian_period) % (2 * np.pi)
    return ultradian_phase, circadian_phase







ultradian_period = calculate_ultradian_period(signal, times)

ultradian_phases, circadian_phases = extract_phases(signal, times, ultradian_period)


def extract_ultradian_cycle(signal, times, start_time, ultradian_period):
    start_idx = np.abs(times - start_time).argmin() 
    end_time = start_time + ultradian_period
    extracted_indices = (times >= start_time) & (times <= end_time)
    extracted_signal = signal[extracted_indices]
    extracted_times = times[extracted_indices]
    
    return extracted_times, extracted_signal


# Cut off 24hr signal

'''